[tool.black]
line-length = 99
target-version = ['py310', 'py311', 'py312']

[tool.isort]
profile = "black"
line_length = 99
skip_gitignore = true

[tool.pylint.format]
max-line-length = 99

[tool.ruff]
line-length = 99

[tool.ruff.pycodestyle]
max-doc-length = 72
